clustering_variables:
  # - ClientKnowledgeExperience
  - Age
  - IncomeNeed
  - RiskPropension
  - ProtectionNeed
  # - IncomeHighLow
  # - LongTermCareNeed
  # - ClientPotentialIndex
  - InheritanceIndex
plotting_vars:
  - RiskPropension
  - ProtectionNeed
