clustering_variables:
  # - ClientKnowledgeExperience
  - Age
  - IncomeNeed
  - RiskPropension
  - ProtectionNeed
  - LongTermCareNeed
  - InheritanceIndex
plotting_vars:
  - RiskPropension
  - ProtectionNeed
